name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Lambda deployment package
        run: |
          # Create a temporary directory to hold Lambda deployment package contents
          mkdir lambda_package
          
          # Copy the Lambda handler code and any other dependencies into the package directory
          cp -r aws_lambda.py lambda_package/
          # You may need to copy other dependencies or resources as required

          # Compress the contents of the package directory into a ZIP archive
          zip -r lambda_package.zip lambda_package
          
          # Clean up the temporary directory
          rm -rf lambda_package
        working-directory: $GITHUB_WORKSPACE

  deploy_lambda:
    needs: build  # Ensure that the 'deploy_lambda' job runs after 'build' completes successfully
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Lambda function
        run: |
          aws lambda create-function \
            --function-name invokeGlobalWeather \
            --runtime python3.11 \
            --handler aws_lambda.lambda_handler \
            --role arn:aws:iam::256522976328:role/AdministratorAccess \
            --zip-file fileb://lambda_package.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-north-1
